[system]
version = "0.1.1"
author = "Kristjan ESPERANTO"
description = "A lightweight, decentralized monitoring tool designed to run independently on a local system."
license = "ISC"
repository = "https://github.com/KristjanESPERANTO/LoneWatcher"

[gui]
language = "en"               # Language for the GUI, options: "en" and "de"
custom_title = ""             # Title of the GUI window - if not set, default is system name + version
char_width_multiplier = 6     # Multiplier for character width in the GUI
additional_row_width = 150    # Additional width for each row in the GUI
max_row_width = 500           # Maximum width for each row in the GUI
font_size = 14                # Font size for the GUI

[timer]
initial_minimize_delay = 3    # Time before minimizing window on first run
status_check_interval = 0.5   # Time between individual status checks
all_green_interval = 60       # Sleep time when all systems are ok
alert_interval = 15           # Sleep time when there are issues