[system]
version = "0.1.1"
author = "Kristjan ESPERANTO"
description = "A lightweight, decentralized monitoring tool designed to run independently on a local system."
license = "ISC"
repository = "https://github.com/KristjanESPERANTO/LoneWatcher"

[gui]
custom_title = "" # Title of the GUI window - if not set, default is system name + version
char_width_multiplier = 6 # Multiplier for character width in the GUI
additional_row_width = 150 # Additional width for each row in the GUI
max_row_width = 500 # Maximum width for each row in the GUI